name: Maven Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REPO_NAME: ${{ github.event.repository.name }} 
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Del package
      run: gh release delete "UniversalItemsLib"
      continue-on-error: true
    - name: Publish to GitHub Packages Apache Maven
      run: "gh release create UniversalItemsLib ./target/UniversalItemsLib-1.0.jar"
